bookmarks/urls.py
from django.urls import path, include
from django.urls import re_path
from django.views.generic import RedirectView

from bookmarks import views
from bookmarks.api.routes import router
from bookmarks.feeds import AllBookmarksFeed, UnreadBookmarksFeed
from bookmarks.views import partials

app_name = 'bookmarks'
urlpatterns = [
    # Redirect root to bookmarks index
    re_path(r'^$', RedirectView.as_view(pattern_name='bookmarks:index', permanent=False)),
    # Bookmarks
    path('bookmarks', views.bookmarks.index, name='index'),
    path('bookmarks/action', views.bookmarks.index_action, name='index.action'),
    path('bookmarks/archived', views.bookmarks.archived, name='archived'),
    path('bookmarks/archived/action', views.bookmarks.archived_action, name='archived.action'),
    path('bookmarks/shared', views.bookmarks.shared, name='shared'),
    path('bookmarks/shared/action', views.bookmarks.shared_action, name='shared.action'),
    path('bookmarks/new', views.bookmarks.new, name='new'),
    path('bookmarks/close', views.bookmarks.close, name='close'),
    path('bookmarks/<int:bookmark_id>/edit', views.bookmarks.edit, name='edit'),
    # Partials
    path('bookmarks/partials/bookmark-list/active', partials.active_bookmark_list,
         name='partials.bookmark_list.active'),
    path('bookmarks/partials/tag-cloud/active', partials.active_tag_cloud, name='partials.tag_cloud.active'),
    path('bookmarks/partials/bookmark-list/archived', partials.archived_bookmark_list,
         name='partials.bookmark_list.archived'),
    path('bookmarks/partials/tag-cloud/archived', partials.archived_tag_cloud, name='partials.tag_cloud.archived'),
    path('bookmarks/partials/bookmark-list/shared', partials.shared_bookmark_list,
         name='partials.bookmark_list.shared'),
    path('bookmarks/partials/tag-cloud/shared', partials.shared_tag_cloud, name='partials.tag_cloud.shared'),
    # Settings
    path('settings', views.settings.general, name='settings.index'),
    path('settings/general', views.settings.general, name='settings.general'),
    path('settings/integrations', views.settings.integrations, name='settings.integrations'),
    path('settings/import', views.settings.bookmark_import, name='settings.import'),
    path('settings/export', views.settings.bookmark_export, name='settings.export'),
    # Toasts
    path('toasts/acknowledge', views.toasts.acknowledge, name='toasts.acknowledge'),
    # API
    path('api/', include(router.urls), name='api'),
    # Feeds
    path('feeds/<str:feed_key>/all', AllBookmarksFeed(), name='feeds.all'),
    path('feeds/<str:feed_key>/unread', UnreadBookmarksFeed(), name='feeds.unread'),
    # Health check
    path('health', views.health, name='health'),
    # Manifest
    path("manifest.json", views.manifest, name='manifest')
]

siteroot/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, include

from bookmarks.admin import linkding_admin_site
from .settings import ALLOW_REGISTRATION, DEBUG

urlpatterns = [
    path('admin/', linkding_admin_site.urls),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True,
                                                extra_context=dict(allow_registration=ALLOW_REGISTRATION)),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', include('bookmarks.urls')),
]

if settings.LD_CONTEXT_PATH:
    urlpatterns = [path(settings.LD_CONTEXT_PATH, include(urlpatterns))]

if DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

if ALLOW_REGISTRATION:
    urlpatterns.append(path('', include('django_registration.backends.one_step.urls')))

bookmarks/api/routes.py
from rest_framework import viewsets, mixins, status
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.routers import DefaultRouter

from bookmarks import queries
from bookmarks.api.serializers import BookmarkSerializer, TagSerializer, UserProfileSerializer
from bookmarks.models import Bookmark, BookmarkSearch, Tag, User
from bookmarks.services.bookmarks import archive_bookmark, unarchive_bookmark, website_loader
from bookmarks.services.website_loader import WebsiteMetadata


class BookmarkViewSet(viewsets.GenericViewSet,
                      mixins.ListModelMixin,
                      mixins.RetrieveModelMixin,
                      mixins.CreateModelMixin,
                      mixins.UpdateModelMixin,
                      mixins.DestroyModelMixin):
    serializer_class = BookmarkSerializer

    def get_permissions(self):
        # Allow unauthenticated access to shared bookmarks.
        # The shared action should still filter bookmarks so that
        # unauthenticated users only see bookmarks from users that have public
        # sharing explicitly enabled
        if self.action == 'shared':
            return [AllowAny()]

        # Otherwise use default permissions which should require authentication
        return super().get_permissions()

    def get_queryset(self):
        user = self.request.user
        # For list action, use query set that applies search and tag projections
        if self.action == 'list':
            search = BookmarkSearch.from_request(self.request.GET)
            return queries.query_bookmarks(user, user.profile, search)

        # For single entity actions use default query set without projections
        return Bookmark.objects.all().filter(owner=user)

    def get_serializer_context(self):
        return {'user': self.request.user}

    @action(methods=['get'], detail=False)
    def archived(self, request):
        user = request.user
        search = BookmarkSearch.from_request(request.GET)
        query_set = queries.query_archived_bookmarks(user, user.profile, search)
        page = self.paginate_queryset(query_set)
        serializer = self.get_serializer_class()
        data = serializer(page, many=True).data
        return self.get_paginated_response(data)

    @action(methods=['get'], detail=False)
    def shared(self, request):
        search = BookmarkSearch.from_request(request.GET)
        user = User.objects.filter(username=search.user).first()
        public_only = not request.user.is_authenticated
        query_set = queries.query_shared_bookmarks(user, request.user_profile, search, public_only)
        page = self.paginate_queryset(query_set)
        serializer = self.get_serializer_class()
        data = serializer(page, many=True).data
        return self.get_paginated_response(data)

    @action(methods=['post'], detail=True)
    def archive(self, request, pk):
        bookmark = self.get_object()
        archive_bookmark(bookmark)
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(methods=['post'], detail=True)
    def unarchive(self, request, pk):
        bookmark = self.get_object()
        unarchive_bookmark(bookmark)
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(methods=['get'], detail=False)
    def check(self, request):
        url = request.GET.get('url')
        bookmark = Bookmark.objects.filter(owner=request.user, url=url).first()
        existing_bookmark_data = self.get_serializer(bookmark).data if bookmark else None

        # Either return metadata from existing bookmark, or scrape from URL
        if bookmark:
            metadata = WebsiteMetadata(url, bookmark.website_title, bookmark.website_description)
        else:
            metadata = website_loader.load_website_metadata(url)

        return Response({
            'bookmark': existing_bookmark_data,
            'metadata': metadata.to_dict()
        }, status=status.HTTP_200_OK)


class TagViewSet(viewsets.GenericViewSet,
                 mixins.ListModelMixin,
                 mixins.RetrieveModelMixin,
                 mixins.CreateModelMixin):
    serializer_class = TagSerializer

    def get_queryset(self):
        user = self.request.user
        return Tag.objects.all().filter(owner=user)

    def get_serializer_context(self):
        return {'user': self.request.user}


class UserViewSet(viewsets.GenericViewSet):
    @action(methods=['get'], detail=False)
    def profile(self, request):
        return Response(UserProfileSerializer(request.user.profile).data)


router = DefaultRouter()
router.register(r'bookmarks', BookmarkViewSet, basename='bookmark')
router.register(r'tags', TagViewSet, basename='tag')
router.register(r'user', UserViewSet, basename='user')

bookmarks/views/health.py
from django.db import connections
from django.http import JsonResponse

from bookmarks.views.settings import app_version


def health(request):
    code = 200
    response = {
        'version': app_version,
        'status': 'healthy'
    }

    try:
        connections['default'].ensure_connection()
    except Exception:
        response['status'] = 'unhealthy'
        code = 500

    return JsonResponse(response, status=code)

bookmarks/views/manifest.py
from django.http import JsonResponse
from django.conf import settings


def manifest(request):
    response = {
        "short_name": "linkding",
        "start_url": "bookmarks",
        "display": "standalone",
        "scope": "/" + settings.LD_CONTEXT_PATH
    }

    return JsonResponse(response, status=200)

bookmarks/views/settings.py
import logging
import time
from functools import lru_cache

import requests
from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import prefetch_related_objects
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from rest_framework.authtoken.models import Token

from bookmarks.models import Bookmark, BookmarkSearch, UserProfileForm, FeedToken
from bookmarks.services import exporter, tasks
from bookmarks.services import importer
from bookmarks.utils import app_version

logger = logging.getLogger(__name__)


@login_required
def general(request):
    profile_form = None
    enable_refresh_favicons = django_settings.LD_ENABLE_REFRESH_FAVICONS
    update_profile_success_message = None
    refresh_favicons_success_message = None
    import_success_message = _find_message_with_tag(messages.get_messages(request), 'bookmark_import_success')
    import_errors_message = _find_message_with_tag(messages.get_messages(request), 'bookmark_import_errors')
    version_info = get_version_info(get_ttl_hash())

    if request.method == 'POST':
        if 'update_profile' in request.POST:
            profile_form = update_profile(request)
            update_profile_success_message = 'Profile updated'
        if 'refresh_favicons' in request.POST:
            tasks.schedule_refresh_favicons(request.user)
            refresh_favicons_success_message = 'Scheduled favicon update. This may take a while...'

    if not profile_form:
        profile_form = UserProfileForm(instance=request.user_profile)

    return render(request, 'settings/general.html', {
        'form': profile_form,
        'enable_refresh_favicons': enable_refresh_favicons,
        'update_profile_success_message': update_profile_success_message,
        'refresh_favicons_success_message': refresh_favicons_success_message,
        'import_success_message': import_success_message,
        'import_errors_message': import_errors_message,
        'version_info': version_info,
    })


def update_profile(request):
    user = request.user
    profile = user.profile
    favicons_were_enabled = profile.enable_favicons
    form = UserProfileForm(request.POST, instance=profile)
    if form.is_valid():
        form.save()
        if profile.enable_favicons and not favicons_were_enabled:
            tasks.schedule_bookmarks_without_favicons(request.user)
    return form


# Cache API call response, for one hour when using get_ttl_hash with default params
@lru_cache(maxsize=1)
def get_version_info(ttl_hash=None):
    latest_version = None
    try:
        latest_version_url = 'https://api.github.com/repos/sissbruecker/linkding/releases/latest'
        response = requests.get(latest_version_url, timeout=5)
        json = response.json()
        if response.status_code == 200 and 'name' in json:
            latest_version = json['name'][1:]
    except requests.exceptions.RequestException:
        pass

    latest_version_info = ''
    if latest_version == app_version:
        latest_version_info = ' (latest)'
    elif latest_version is not None:
        latest_version_info = f' (latest: {latest_version})'

    return f'{app_version}{latest_version_info}'


def get_ttl_hash(seconds=3600):
    """Return the same value within `seconds` time period"""
    return round(time.time() / seconds)


@login_required
def integrations(request):
    application_url = request.build_absolute_uri(reverse('bookmarks:new'))
    api_token = Token.objects.get_or_create(user=request.user)[0]
    feed_token = FeedToken.objects.get_or_create(user=request.user)[0]
    all_feed_url = request.build_absolute_uri(reverse('bookmarks:feeds.all', args=[feed_token.key]))
    unread_feed_url = request.build_absolute_uri(reverse('bookmarks:feeds.unread', args=[feed_token.key]))
    return render(request, 'settings/integrations.html', {
        'application_url': application_url,
        'api_token': api_token.key,
        'all_feed_url': all_feed_url,
        'unread_feed_url': unread_feed_url,
    })


@login_required
def bookmark_import(request):
    import_file = request.FILES.get('import_file')
    import_options = importer.ImportOptions(map_private_flag=request.POST.get('map_private_flag') == 'on')

    if import_file is None:
        messages.error(request, 'Please select a file to import.', 'bookmark_import_errors')
        return HttpResponseRedirect(reverse('bookmarks:settings.general'))

    try:
        content = import_file.read().decode()
        result = importer.import_netscape_html(content, request.user, import_options)
        success_msg = str(result.success) + ' bookmarks were successfully imported.'
        messages.success(request, success_msg, 'bookmark_import_success')
        if result.failed > 0:
            err_msg = str(result.failed) + ' bookmarks could not be imported. Please check the logs for more details.'
            messages.error(request, err_msg, 'bookmark_import_errors')
    except:
        logging.exception('Unexpected error during bookmark import')
        messages.error(request, 'An error occurred during bookmark import.', 'bookmark_import_errors')
        pass

    return HttpResponseRedirect(reverse('bookmarks:settings.general'))


@login_required
def bookmark_export(request):
    # noinspection PyBroadException
    try:
        bookmarks = Bookmark.objects.filter(owner=request.user)
        # Prefetch tags to prevent n+1 queries
        prefetch_related_objects(bookmarks, 'tags')
        file_content = exporter.export_netscape_html(bookmarks)

        response = HttpResponse(content_type='text/plain; charset=UTF-8')
        response['Content-Disposition'] = 'attachment; filename="bookmarks.html"'
        response.write(file_content)

        return response
    except:
        return render(request, 'settings/general.html', {
            'export_error': 'An error occurred during bookmark export.'
        })


def _find_message_with_tag(messages, tag):
    for message in messages:
        if message.extra_tags == tag:
            return message

bookmarks/views/toasts.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

from bookmarks.models import Toast
from bookmarks.utils import get_safe_return_url


@login_required
def acknowledge(request):
    toast_id = request.POST['toast']
    try:
        toast = Toast.objects.get(pk=toast_id, owner=request.user)
    except Toast.DoesNotExist:
        raise Http404('Toast does not exist')
    toast.acknowledged = True
    toast.save()

    return_url = get_safe_return_url(request.GET.get('return_url'), reverse('bookmarks:index'))
    return HttpResponseRedirect(return_url)

bookmarks/templates/bookmarks/archive.html
{% extends "bookmarks/layout.html" %}
{% load static %}
{% load shared %}
{% load bookmarks %}

{% block content %}
  <div class="bookmarks-page grid columns-md-1"
       ld-bulk-edit
       ld-bookmark-page
       bookmarks-url="{% url 'bookmarks:partials.bookmark_list.archived' %}"
       tags-url="{% url 'bookmarks:partials.tag_cloud.archived' %}">

    {# Bookmark list #}
    <section class="content-area col-2">
      <div class="content-area-header mb-0">
        <h2>Archived bookmarks</h2>
        <div class="header-controls">
          {% bookmark_search bookmark_list.search tag_cloud.tags mode='archived' %}
          {% include 'bookmarks/bulk_edit/toggle.html' %}
          <button ld-modal modal-content=".tag-cloud" class="btn ml-2 show-md">Tags</button>
        </div>
      </div>

      <form class="bookmark-actions"
            action="{{ bookmark_list.action_url|safe }}"
            method="post" autocomplete="off">
        {% csrf_token %}
        {% include 'bookmarks/bulk_edit/bar.html' with disable_actions='bulk_archive' %}

        <div class="bookmark-list-container">
          {% include 'bookmarks/bookmark_list.html' %}
        </div>
      </form>
    </section>

    {# Tag cloud #}
    <section class="content-area col-1 hide-md">
      <div class="content-area-header">
        <h2>Tags</h2>
      </div>
      <div class="tag-cloud-container">
        {% include 'bookmarks/tag_cloud.html' %}
      </div>
    </section>
  </div>

  <script src="{% static "bundle.js" %}?v={{ app_version }}"></script>
{% endblock %}

bookmarks/templates/bookmarks/close.html
{% extends "bookmarks/layout.html" %}

{% block content %}
  <script type="application/javascript">
    window.close()
  </script>
  <p>You can now close this window.</p>
{% endblock %}

bookmarks/templates/bookmarks/edit.html
{% extends 'bookmarks/layout.html' %}
{% load bookmarks %}

{% block content %}
  <section class="content-area">
    <div class="content-area-header">
      <h2>Edit bookmark</h2>
    </div>
    <form action="{% url 'bookmarks:edit' bookmark_id %}?return_url={{ return_url|urlencode }}" method="post"
          class="width-50 width-md-100" novalidate>
      {% bookmark_form form return_url bookmark_id %}
    </form>
  </section>
{% endblock %}

bookmarks/templates/bookmarks/layout.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
{# Use data attributes as storage for access in static scripts #}
<html lang="en" data-api-base-url="{% url 'bookmarks:api-root' %}">
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="{% static 'favicon.png' %}"/>
  <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
  <link rel="manifest" href="{% url 'bookmarks:manifest' %}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimal-ui">
  <meta name="description" content="Self-hosted bookmark service">
  <meta name="robots" content="index,follow">
  <meta name="author" content="Sascha Ißbrücker">
  <title>linkding</title>
  {# Include SASS styles, files are resolved from bookmarks/styles #}
  {# Include specific theme variant based on user profile setting #}
  {% if request.user_profile.theme == 'light' %}
    <link href="{% sass_src 'theme-light.scss' %}?v={{ app_version }}" rel="stylesheet" type="text/css"/>
  {% elif request.user_profile.theme == 'dark' %}
    <link href="{% sass_src 'theme-dark.scss' %}?v={{ app_version }}" rel="stylesheet" type="text/css"/>
  {% else %}
    {# Use auto theme as fallback #}
    <link href="{% sass_src 'theme-dark.scss' %}?v={{ app_version }}" rel="stylesheet" type="text/css"
          media="(prefers-color-scheme: dark)"/>
    <link href="{% sass_src 'theme-light.scss' %}?v={{ app_version }}" rel="stylesheet" type="text/css"
          media="(prefers-color-scheme: light)"/>
  {% endif %}
</head>
<body ld-global-shortcuts>

<div class="d-none">
  <svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="ld-icon-unread" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
            stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0"></path>
      <path d="M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0"></path>
      <path d="M3 6l0 13"></path>
      <path d="M12 6l0 13"></path>
      <path d="M21 6l0 13"></path>
    </symbol>
  </svg>
  <svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="ld-icon-read" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
            stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M3 19a9 9 0 0 1 9 0a9 9 0 0 1 5.899 -1.096"></path>
      <path d="M3 6a9 9 0 0 1 2.114 -.884m3.8 -.21c1.07 .17 2.116 .534 3.086 1.094a9 9 0 0 1 9 0"></path>
      <path d="M3 6v13"></path>
      <path d="M12 6v2m0 4v7"></path>
      <path d="M21 6v11"></path>
      <path d="M3 3l18 18"></path>
    </symbol>
  </svg>
  <svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="ld-icon-share" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
            stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M6 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
      <path d="M18 6m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
      <path d="M18 18m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
      <path d="M8.7 10.7l6.6 -3.4"></path>
      <path d="M8.7 13.3l6.6 3.4"></path>
    </symbol>
  </svg>
  <svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="ld-icon-unshare" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
            stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M6 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
      <path d="M18 6m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
      <path d="M15.861 15.896a3 3 0 0 0 4.265 4.22m.578 -3.417a3.012 3.012 0 0 0 -1.507 -1.45"></path>
      <path d="M8.7 10.7l1.336 -.688m2.624 -1.352l2.64 -1.36"></path>
      <path d="M8.7 13.3l6.6 3.4"></path>
      <path d="M3 3l18 18"></path>
    </symbol>
  </svg>
  <svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="ld-icon-note" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
            stroke-linecap="round" stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
      <path d="M5 3m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z"></path>
      <path d="M9 7l6 0"></path>
      <path d="M9 11l6 0"></path>
      <path d="M9 15l4 0"></path>
    </symbol>
  </svg>
</div>

<header class="container">
  {% if has_toasts %}
    <div class="toasts">
      <form action="{% url 'bookmarks:toasts.acknowledge' %}?return_url={{ request.path | urlencode }}" method="post">
        {% csrf_token %}
        {% for toast in toast_messages %}
          <div class="toast">
            {{ toast.message }}
            <button type="submit" name="toast" value="{{ toast.id }}" class="btn btn-clear float-right"></button>
          </div>
        {% endfor %}
      </form>
    </div>
  {% endif %}
  <div class="d-flex justify-between">
    <a href="{% url 'bookmarks:index' %}" class="d-flex align-center">
      <img class="logo" src="{% static 'logo.png' %}" alt="Application logo">
      <h1>LINKDING</h1>
    </a>
    {% if request.user.is_authenticated %}
      {# Only show nav items menu when logged in #}
      {% include 'bookmarks/nav_menu.html' %}
    {% elif has_public_shares %}
      {# Otherwise show link to shared bookmarks if there are publicly shared bookmarks #}
      <a href="{% url 'bookmarks:shared' %}" class="btn btn-link">Shared bookmarks</a>
    {% endif %}
  </div>
</header>
<div class="content container">
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

bookmarks/templates/bookmarks/nav_menu.html
{% load shared %}
{% htmlmin %}
{# Basic menu list #}
<div class="hide-md">
  <a href="{% url 'bookmarks:new' %}" class="btn btn-primary mr-2">Add bookmark</a>
  <div class="dropdown">
    <a href="#" class="btn btn-link dropdown-toggle" tabindex="0" style="padding-right: 0.2rem">
      Bookmarks
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"
           style="height:1rem;width:1rem;vertical-align: text-bottom;">
        <path fill-rule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clip-rule="evenodd"/>
      </svg>
    </a>
    <ul class="menu">
      <li>
        <a href="{% url 'bookmarks:index' %}" class="btn btn-link">Active</a>
      </li>
      <li>
        <a href="{% url 'bookmarks:archived' %}" class="btn btn-link">Archived</a>
      </li>
      {% if request.user_profile.enable_sharing %}
        <li>
          <a href="{% url 'bookmarks:shared' %}" class="btn btn-link">Shared</a>
        </li>
      {% endif %}
      <li>
        <a href="{% url 'bookmarks:index' %}?unread=yes" class="btn btn-link">Unread</a>
      </li>
      <li>
        <a href="{% url 'bookmarks:index' %}?q=!untagged" class="btn btn-link">Untagged</a>
      </li>
    </ul>
  </div>
  <a href="{% url 'bookmarks:settings.index' %}" class="btn btn-link">Settings</a>
  <a href="{% url 'logout' %}" class="btn btn-link">Logout</a>
</div>
{# Menu drop-down for smaller devices #}
<div class="show-md">
  <a href="{% url 'bookmarks:new' %}" class="btn btn-primary">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
         style="width: 24px; height: 24px">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
    </svg>
  </a>
  <div ld-dropdown class="dropdown dropdown-right">
    <a href="#" class="btn btn-link dropdown-toggle" tabindex="0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
           style="width: 24px; height: 24px">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
      </svg>
    </a>
    <!-- menu component -->
    <ul class="menu">
      <li>
        <a href="{% url 'bookmarks:index' %}" class="btn btn-link">Bookmarks</a>
      </li>
      <li style="padding-left: 1rem">
        <a href="{% url 'bookmarks:archived' %}" class="btn btn-link">Archived</a>
      </li>
      {% if request.user_profile.enable_sharing %}
        <li style="padding-left: 1rem">
          <a href="{% url 'bookmarks:shared' %}" class="btn btn-link">Shared</a>
        </li>
      {% endif %}
      <li style="padding-left: 1rem">
        <a href="{% url 'bookmarks:index' %}?unread=yes" class="btn btn-link">Unread</a>
      </li>
      <li style="padding-left: 1rem">
        <a href="{% url 'bookmarks:index' %}?q=!untagged" class="btn btn-link">Untagged</a>
      </li>
      <li>
        <a href="{% url 'bookmarks:settings.index' %}" class="btn btn-link">Settings</a>
      </li>
      <li>
        <a href="{% url 'logout' %}" class="btn btn-link">Logout</a>
      </li>
    </ul>
  </div>
</div>
{% endhtmlmin %}

bookmarks/templates/bookmarks/new.html
{% extends 'bookmarks/layout.html' %}
{% load bookmarks %}

{% block content %}
  <section class="content-area">
    <div class="content-area-header">
      <h2>New bookmark</h2>
    </div>
    <form action="{% url 'bookmarks:new' %}" method="post" class="width-50 width-md-100" novalidate>
      {% bookmark_form form return_url auto_close=auto_close %}
    </form>
  </section>
{% endblock %}